
POST http://localhost:3001/register
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john@doe.com",
    "password": "123"
}

###

POST http://localhost:3001/login
Content-Type: application/json

{
    "email": "john@doe.com",
    "password": "123"
}

###

POST http://localhost:3001/categories
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwODUzMjIzYS1hMmEyLTQ0Y2YtOWIwYy04ODMxZDQxMGE5ZTIiLCJpYXQiOjE3MTE0NjI3MDAsImV4cCI6MTcxMTQ2NjMwMH0.XGmosyoPrFnvN8sBi2QAQXS5yndK7WCjUX5owVneEbQ
Content-Type: application/json

{
  "title": "Salário",
  "color": "#10b981",
  "expense": false
}

###


GET  http://localhost:3001/categories
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwODUzMjIzYS1hMmEyLTQ0Y2YtOWIwYy04ODMxZDQxMGE5ZTIiLCJpYXQiOjE3MTE0NjI3MDAsImV4cCI6MTcxMTQ2NjMwMH0.XGmosyoPrFnvN8sBi2QAQXS5yndK7WCjUX5owVneEbQ

###


PUT  http://localhost:3001/category/edf80731-bc25-4744-a7ae-e763a2f6f164
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwODUzMjIzYS1hMmEyLTQ0Y2YtOWIwYy04ODMxZDQxMGE5ZTIiLCJpYXQiOjE3MTE0NjI3MDAsImV4cCI6MTcxMTQ2NjMwMH0.XGmosyoPrFnvN8sBi2QAQXS5yndK7WCjUX5owVneEbQ
Content-Type: application/json

{
  "title": "Salario566666",
  "color": "#10b981",
  "expense": false
}

###

DELETE  http://localhost:3001/category/edf80731-bc25-4744-a7ae-e763a2f6f164
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwODUzMjIzYS1hMmEyLTQ0Y2YtOWIwYy04ODMxZDQxMGE5ZTIiLCJpYXQiOjE3MTE0NjI3MDAsImV4cCI6MTcxMTQ2NjMwMH0.XGmosyoPrFnvN8sBi2QAQXS5yndK7WCjUX5owVneEbQ


###


