
POST https://expense-tracker-api-qwnr.onrender.com/register
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john@doe.com",
    "password": "123"
}

###

POST https://expense-tracker-api-qwnr.onrender.com/login
Content-Type: application/json

{
    "email": "john@doe1.com",
    "password": "123"
}

###

POST https://expense-tracker-api-qwnr.onrender.com/categories
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzYjY1ZDlmOS02MzY2LTRmODUtOTBiMy0xOTQxMmJkMTZjNjciLCJpYXQiOjE3MTEzNzQ4NjgsImV4cCI6MTcxMTM3ODQ2OH0.PBRHrtjmvWnnz9vvuyC0rAQbxP4mGt3BglQnXmWZML4
Content-Type: application/json

{
  "title": "Salário",
  "color": "#10b981",
  "expense": false
}

###


GET  https://expense-tracker-api-qwnr.onrender.com/categories
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzYjY1ZDlmOS02MzY2LTRmODUtOTBiMy0xOTQxMmJkMTZjNjciLCJpYXQiOjE3MTEzNzQ4NjgsImV4cCI6MTcxMTM3ODQ2OH0.PBRHrtjmvWnnz9vvuyC0rAQbxP4mGt3BglQnXmWZML4

###


PUT  https://expense-tracker-api-qwnr.onrender.com/category/0d6f17b8-7127-4f16-b146-00be806e1899
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzYjY1ZDlmOS02MzY2LTRmODUtOTBiMy0xOTQxMmJkMTZjNjciLCJpYXQiOjE3MTEzNzQ4NjgsImV4cCI6MTcxMTM3ODQ2OH0.PBRHrtjmvWnnz9vvuyC0rAQbxP4mGt3BglQnXmWZML4
Content-Type: application/json

{
  "title": "Salario566666",
  "color": "#10b981",
  "expense": false
}

###

DELETE  https://expense-tracker-api-qwnr.onrender.com/category/0e476075-7ddd-4e5f-a4f6-db98f7a84164
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzYjY1ZDlmOS02MzY2LTRmODUtOTBiMy0xOTQxMmJkMTZjNjciLCJpYXQiOjE3MTEzNzQ4NjgsImV4cCI6MTcxMTM3ODQ2OH0.PBRHrtjmvWnnz9vvuyC0rAQbxP4mGt3BglQnXmWZML4


###


