POST https://expense-tracker-api-qwnr.onrender.com/register
Content-Type: application/json

{
    "name": "Jonh Doe",
    "email": "john@doe1.com",
    "password": "123"
}

###

POST https://expense-tracker-api-qwnr.onrender.com/login
Content-Type: application/json

{
    "email": "john@doe1.com",
    "password": "123"
}


###


POST http://localhost:3001/records
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhOThlYTg3YS02OWY0LTQ4ZWUtOGFhYS0zNDZjMDk4OTljYzciLCJpYXQiOjE3MTEzMzA2NzgsImV4cCI6MTcxMTMzNDI3OH0.ThqjTGiKuUynnu50lEjIwW-f7cJC-K995cWcFqnBM2s
Content-Type: application/json

{
  "date": "2024-03-16T12:00:00Z",
  "value": 20.50,
  "category": "FARMACIA",
  "description": "ALKK"

}


###


GET http://localhost:3001/records
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhOThlYTg3YS02OWY0LTQ4ZWUtOGFhYS0zNDZjMDk4OTljYzciLCJpYXQiOjE3MTEzMzA2NzgsImV4cCI6MTcxMTMzNDI3OH0.ThqjTGiKuUynnu50lEjIwW-f7cJC-K995cWcFqnBM2s

###


DELETE http://localhost:3001/record/68e27cea-45b7-4011-b423-9268c46790ac
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhOThlYTg3YS02OWY0LTQ4ZWUtOGFhYS0zNDZjMDk4OTljYzciLCJpYXQiOjE3MTEzMzA2NzgsImV4cCI6MTcxMTMzNDI3OH0.ThqjTGiKuUynnu50lEjIwW-f7cJC-K995cWcFqnBM2s


###


PUT http://localhost:3001/record/68e27cea-45b7-4011-b423-9268c46790ac
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhOThlYTg3YS02OWY0LTQ4ZWUtOGFhYS0zNDZjMDk4OTljYzciLCJpYXQiOjE3MTEzMzA2NzgsImV4cCI6MTcxMTMzNDI3OH0.ThqjTGiKuUynnu50lEjIwW-f7cJC-K995cWcFqnBM2s
Content-Type: application/json

{
  "date": "2024-01-16T12:00:00Z",
  "value": 80.90,
  "category": "Mercado",
  "description": "mercado"
}

###

POST  http://localhost:3001/refresh
# Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjYsImlhdCI6MTcwNjM5NzEyOSwiZXhwIjoxNzA3MDAxOTI5fQ.0tDdLAiPv44bwFYRF6v-Ucc-5npHPpgZug9bMpVZ8HE
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjcsImlhdCI6MTcwNzAxNzIxMiwiZXhwIjoxNzA3NjIyMDEyfQ.vUkx3h-l7gROyF_U3UkEVu6onN1kikUXoCxG1CTU9rk"
}
###


PUT http://localhost:3001/records/update
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhOThlYTg3YS02OWY0LTQ4ZWUtOGFhYS0zNDZjMDk4OTljYzciLCJpYXQiOjE3MTEzMzA2NzgsImV4cCI6MTcxMTMzNDI3OH0.ThqjTGiKuUynnu50lEjIwW-f7cJC-K995cWcFqnBM2s
Content-Type: application/json

{
  "currentName": "mercearia",
  "updateName": "mercado"
}

###