POST https://expense-tracker-api-qwnr.onrender.com/register
Content-Type: application/json

{
    "name": "Jonh Doe",
    "email": "john@doe1.com",
    "password": "123"
}

###

POST https://expense-tracker-api-qwnr.onrender.com/login
Content-Type: application/json

{
    "email": "john@doe1.com",
    "password": "123"
}


###


POST http://localhost:3001/records
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJiZDM2NDgxOC04ZGJiLTQ0ZDEtOWVhZC1iZDg4NWYxOGIyNWYiLCJpYXQiOjE3MTE0NjExNTUsImV4cCI6MTcxMTQ2NDc1NX0.4SpPGa0FCIaZ--KZcIZJFLmc_WLkYkmGPtXjzEK6grM
Content-Type: application/json

{
  "date": "2024-03-16T12:00:00Z",
  "value": 20.50,
  "category": "FARMACIA",
  "description": "ALKK"

}


###


GET http://localhost:3001/records
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJiZDM2NDgxOC04ZGJiLTQ0ZDEtOWVhZC1iZDg4NWYxOGIyNWYiLCJpYXQiOjE3MTE0NjExNTUsImV4cCI6MTcxMTQ2NDc1NX0.4SpPGa0FCIaZ--KZcIZJFLmc_WLkYkmGPtXjzEK6grM

###


DELETE http://localhost:3001/record/abc4c651-02c5-4b6d-978c-63c99b9b9fbb
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJiZDM2NDgxOC04ZGJiLTQ0ZDEtOWVhZC1iZDg4NWYxOGIyNWYiLCJpYXQiOjE3MTE0NjExNTUsImV4cCI6MTcxMTQ2NDc1NX0.4SpPGa0FCIaZ--KZcIZJFLmc_WLkYkmGPtXjzEK6grM


###


PUT http://localhost:3001/record/abc4c651-02c5-4b6d-978c-63c99b9b9fbb
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJiZDM2NDgxOC04ZGJiLTQ0ZDEtOWVhZC1iZDg4NWYxOGIyNWYiLCJpYXQiOjE3MTE0NjExNTUsImV4cCI6MTcxMTQ2NDc1NX0.4SpPGa0FCIaZ--KZcIZJFLmc_WLkYkmGPtXjzEK6grM
Content-Type: application/json

{
  "date": "2024-01-16T12:00:00Z",
  "value": 80.90,
  "category": "Mercado",
  "description": "mercado"
}

###

POST  http://localhost:3001/refresh
# Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjYsImlhdCI6MTcwNjM5NzEyOSwiZXhwIjoxNzA3MDAxOTI5fQ.0tDdLAiPv44bwFYRF6v-Ucc-5npHPpgZug9bMpVZ8HE
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjcsImlhdCI6MTcwNzAxNzIxMiwiZXhwIjoxNzA3NjIyMDEyfQ.vUkx3h-l7gROyF_U3UkEVu6onN1kikUXoCxG1CTU9rk"
}
###


PUT http://localhost:3001/records/update
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJiZDM2NDgxOC04ZGJiLTQ0ZDEtOWVhZC1iZDg4NWYxOGIyNWYiLCJpYXQiOjE3MTE0NjExNTUsImV4cCI6MTcxMTQ2NDc1NX0.4SpPGa0FCIaZ--KZcIZJFLmc_WLkYkmGPtXjzEK6grM
Content-Type: application/json

{
  "currentName": "FARMACIA",
  "updateName": "mercado"
}

###