POST  https://expense-tracker-api-ochre.vercel.app/register
Content-Type: application/json

{
    "name": "Jonh Doe",
    "email": "john@doe.com",
    "password": "123"
}

###

POST https://expense-tracker-api-ochre.vercel.app/login
Content-Type: application/json

{
    "email": "john@doe.com",
    "password": "123"
}

###

POST https://expense-tracker-api-ochre.vercel.app/account
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwMUoxU1JCNDlDNUYwTjI2NEJGQjRYSzVDMSIsImlhdCI6MTcxOTkyOTkyNywiZXhwIjoxNzE5OTMzNTI3fQ.ixdeVBonqAysvR0TINy0RFwCW2QL3dXA64T8VIkUTRA
Content-Type: application/json

{
  "name": "Salário",
  "color": "#10b981",
  "expense": false
}

###


GET https://expense-tracker-api-ochre.vercel.app/account/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwMUoxU1JCNDlDNUYwTjI2NEJGQjRYSzVDMSIsImlhdCI6MTcxOTkyOTkyNywiZXhwIjoxNzE5OTMzNTI3fQ.ixdeVBonqAysvR0TINy0RFwCW2QL3dXA64T8VIkUTRA

###


DELETE https://expense-tracker-api-ochre.vercel.app/record/01HZJXVPM9C0NDGKZF4ZNVHQNS
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwMUoxU1JCNDlDNUYwTjI2NEJGQjRYSzVDMSIsImlhdCI6MTcxOTkyOTkyNywiZXhwIjoxNzE5OTMzNTI3fQ.ixdeVBonqAysvR0TINy0RFwCW2QL3dXA64T8VIkUTRA

###

POST https://expense-tracker-api-ochre.vercel.app/account
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwMUoxU1JCNDlDNUYwTjI2NEJGQjRYSzVDMSIsImlhdCI6MTcxOTkyOTkyNywiZXhwIjoxNzE5OTMzNTI3fQ.ixdeVBonqAysvR0TINy0RFwCW2QL3dXA64T8VIkUTRA
Content-Type: application/json

{
  "name": "NU BANK"
}


###


POST  https://expense-tracker-api-ochre.vercel.app/account/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwMUoxU1JCNDlDNUYwTjI2NEJGQjRYSzVDMSIsImlhdCI6MTcxOTkyOTkyNywiZXhwIjoxNzE5OTMzNTI3fQ.ixdeVBonqAysvR0TINy0RFwCW2QL3dXA64T8VIkUTRA
Content-Type: application/json

{
  "date": "2024-07-16T12:00:00Z",
  "value": 20.50,
  "category": "MERCADO",
  "description": "EDITADO",
  "account_id":"01J1SRB51M4SCE1QC3DTRV8AX2"
}